import { motion } from 'motion/react';

export function FloatingBalloons() {
  const balloons = [
      { color: '#FF6B6B', left: '10%', delay: 0, size: 60 },
          { color: '#4ECDC4', left: '25%', delay: 0.5, size: 50 },
              { color: '#FFE66D', left: '75%', delay: 1, size: 55 },
                  { color: '#FF6B9D', left: '85%', delay: 0.3, size: 65 },
                      { color: '#95E1D3', left: '50%', delay: 0.8, size: 58 },
                        ];
                          
                            return (
                                <div className="absolute inset-0 overflow-hidden pointer-events-none">
                                      {balloons.map((balloon, index) => (
                                              <div key={index} className="absolute" style={{ left: balloon.left }}>
                                                        <motion.div
                                                                    animate={{
                                                                                  y: [0, -20, 0],
                                                                                                x: [0, 10, 0],
                                                                                                            }}
                                                                                                                        transition={{
                                                                                                                                      duration: 4 + index,
                                                                                                                                                    delay: balloon.delay,
                                                                                                                                                                  repeat: Infinity,
                                                                                                                                                                                ease: 'easeInOut',
                                                                                                                                                                                            }}
                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                      width: balloon.size,
                                                                                                                                                                                                                                    height: balloon.size * 1.2,
                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                            className="relative"
                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                  {/* Balloon */}
                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                            className="w-full h-full rounded-full opacity-80"
                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                          backgroundColor: balloon.color,
                                                                                                                                                                                                                                                                                                                                                          boxShadow: `inset -10px -10px 20px rgba(0,0,0,0.1)`,
                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                {/* Balloon shine */}
                                                                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                                                                          className="absolute top-2 left-2 w-4 h-6 bg-white rounded-full opacity-40"
                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* String */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="absolute left-1/2 top-full w-0.5 h-24 bg-gray-400 opacity-60"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{ transform: 'translateX(-50%)' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    